# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-30 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=2000)),
                ('form', models.CharField(max_length=50)),
                ('oath', models.CharField(max_length=50)),
                ('ally', models.CharField(max_length=50)),
            ],
        ),
    ]
